  version: '3.7'

  services:
    web:
      container_name: intern
      build: .
      restart: always
      networks:
        - intrn
      env_file:
        - "vars.env"
      ports:
        - "7890:7890"
      volumes:
      - api:/usr/src/app/
      depends_on:
        - db
    db:
      restart: always
      image: postgres:latest
      env_file:
        - "vars.env"
      networks:
        - intrn
      container_name: db_postgres
      volumes:
        - database_postgres:/var/lib/postgresql/data

  volumes:
    api:
    database_postgres:

  networks:
    intrn: